In [17]:
import numpy as np
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [20]:
a = a.reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a = a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [29]:
b = np.arange(10).reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
b = b.T
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [28]:
np.sqrt(b)

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ]])

In [9]:
import pandas as pd
csv_df = pd.read_csv('cars.csv', delimiter = ";")
