### Homework 3 Numpy Arrays and Pandas

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into a numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [3]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. (2 pts) What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [57]:
df.dtypes

Car              object
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower      float64
Weight          float64
Acceleration    float64
Model             int64
Origin           object
dtype: object

2. (1 pt) `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#The action is called importing as an alias.
#So that it is easier to type when it's functions it has needs to be used would take less time and less chances to make a spelling mistake.

3. (2 pts) Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [45]:
print(f"Car: {df['Car'].ndim}\nMPG: {df['MPG'].ndim}\nCylinders: {df['Cylinders'].ndim}\nDisplacement: {df['Displacement'].ndim}\nHorsepower: {df['Horsepower'].ndim}\nWeight: {df['Weight'].ndim}\nAcceleration: {df['Acceleration'].ndim}\nModel: {df['Model'].ndim}\nOrigin: {df['Origin'].ndim}")

Car: 1
MPG: 1
Cylinders: 1
Displacement: 1
Horsepower: 1
Weight: 1
Acceleration: 1
Model: 1
Origin: 1


4. (3 pts) What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help) (1 pt extra credit)

In [50]:
print(f"Sum: {df['Horsepower'].sum()}\nMinimum: {df['Horsepower'].min()}\nMaximum: {df['Horsepower'].max()}\nMedian: {df['Horsepower'].median()}")

Sum: 42033.0
Minimum: 0.0
Maximum: 230.0
Median: 93.5


5. (2 pts) Select the last element in each subarray (do this with one operation.)

In [55]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])
print(select_more[:,2])

[3 6 9]


6. (2 pts) Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [7]:
np.log(mpg)
#the np.lookfor() function has been removed.  

C:\Users\benpt\AppData\Local\Temp\ipykernel_12536\67066281.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(mpg)


array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

7. (2 pts) Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [78]:
us_array = np.where(df['Origin']=="US",True,False)
us_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

8. (2 pts) Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [81]:
df['Car'][us_array == True]

0      Chevrolet Chevelle Malibu
1              Buick Skylark 320
2             Plymouth Satellite
3                  AMC Rebel SST
4                    Ford Torino
                 ...            
400             Chevrolet Camaro
401              Ford Mustang GL
403                Dodge Rampage
404                  Ford Ranger
405                   Chevy S-10
Name: Car, Length: 254, dtype: object

### Use numpy or pandas to answer the following questions.

9. (3 pts) What is the average horsepower for `Europe` cars? (Hint: create a boolean index of 'US' apply it to horsepower and perform the calculation.)

In [82]:
eu_array = np.where(df['Origin']=="Europe",True,False)
eu_avg = df['Horsepower'][eu_array==True].mean()
print(eu_avg)

78.78082191780823

10. (3 pts) On average are Japanese cars more fuel-efficient than US cars? Show the code that you used to determine this.  

In [90]:
jp_array = np.where(df['Origin']=="Japan",True,False)
jp_avg = df['Horsepower'][jp_array==True].mean()
us_avg = df['Horsepower'][us_array==True].mean()
if jp_avg > us_avg:
    print("Yes, on average Japanese cars are more fuel-efficient than US cars.")
elif jp_avg < us_avg:
    print("No, on average US cars are more fuel-efficient than Japanese cars.")
else:
    print("Neither are more fuel-efficient than the other.")

No, on average US cars are more fuel-efficient than Japanese cars.


11. (3 pts) What is the correlation coefficient of `mpg` and `weight`? What is a correlation coefficient? What does the result indicate about the relationship between mpg and weight? 

In [101]:
mpgweight_cc = np.corrcoef(df['MPG'],df['Weight'])
mpgweight_cc[0,1]
#The correlation coefficient is a statistical measure of the strength of a linear relationship between two variables, which ranges from -1 to 1.
#The result indicates that as mpg increases, weight decreases and vice versa.

-0.7875099405047028

Extra credit: (3 pts) Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin